name: Commonality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        run: pnpm exec commonality check

      - name: Constrain
        run: pnpm exec commonality constrain
